apiVersion: batch/v1
kind: Job
metadata:
  generateName: orbital-demo-cpu-
  namespace: orbital-demo
  labels:
    kueue.x-k8s.io/queue-name: orbital-demo-local
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: cpu-job
          image: registry.k8s.io/e2e-test-images/agnhost:2.53
          command: ["/bin/sh", "-c"]
          args: ["echo cpu-workload; sleep 5"]
          resources:
            requests:
              cpu: "1"
              memory: 256Mi
