apiVersion: v1
kind: ServiceAccount
metadata:
  name: orbital-workflow-runner
  namespace: orbital-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-executor
  namespace: orbital-demo
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-executor-default
  namespace: orbital-demo
subjects:
  - kind: ServiceAccount
    name: orbital-workflow-runner
    namespace: orbital-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow-executor
